### ISSUE TITLE
WErFault errors

### ISSUE THREAD

**Issue by TheDarkMythos** [bytecode77/r77-rootkit#8] opened 2021-03-28 09:42 UTC
After installing it, I get these errors on task manager,
any idea how to fix this?
![Screenshot_1](https://user-images.githubusercontent.com/23459052/112748197-ed253c80-8fc2-11eb-842e-e19c63b75f68.png)

**Comment by bytecode77** [comment] 2021-03-28 10:09
Looks like some injected application is crashing and maybe restarting each time it crashes, causing this "WerFault loop".

Could you check the EventVwr to see which application it is? If you could provide some details on that and the info from EventVwr, I could try to reproduce the issue.

Also, just to keep in mind: If you are implementing r77 in your application, make sure that your application isn't injected by r77. You can do this by using the $77 prefix.

**Comment by TheDarkMythos** [comment] 2021-03-28 10:32
Yes, I know which app it is!! ok, thank you very much! That error comes any time I create a new file with the prefix name. I will now install a new VM and try to reproduce this error and i will let you know.

**Comment by TheDarkMythos** [comment] 2021-03-28 11:02
can I use the old installer C# to install it?

**Comment by bytecode77** [comment] 2021-03-28 11:11
The old installer writes to AppInit_DLLs, but I did not use this technique in the new version, because:

1. It is simply ignored, when secure boot is enabled
2. It only loads, into processes, where kernel32.dll is loaded
3. It requires the DLL to be stored as a file. This file sooner or later gets detected and deleted
4. This registry value is highly suspicious and monitored

You can use it, thought, but I don't recommend it. I would rather investivate in your issue further.



If the app that's crashing is one of your own projects, then please make sure, that:

- r77 is not loaded into the process. Use the file prefix, if possible.
- If the process is fileless and you can't use the prefix, then try to debug. Use the Test Console on your development machine to inject r77 into your application and see what causes the crash. Let me know if there is anything odd that may be a bug in r77.

If the crashing app is a Windows component, then it is a bug that should be fixed. In this case, I need info about the process, the OS and the EventVwr log entry.

**Comment by TheDarkMythos** [comment] 2021-03-28 13:26
Thank you very much for this info!! Here is my idea! I made a builder that takes a URL, places the URL on the stub, and build an executable that includes both the downloader and the rootkit. It loads the rootkit, and then it downloads the payload from the internet (URL) renames the file to the rootkits prefix, and first it executes the rootkit and then the payload with the prefix. I had no errors with the old rootkit but this one is giving me those errors and this is because I still use the old installer. Could you please make also a C# installer if you have the time and the kindness, like you did in the old version of the rootkit?

**Comment by bytecode77** [comment] 2021-03-28 14:00
A question: Do you have the errors in your initial post with the old installer, or with the new installer (1.0.x)? I never tested the new DLL's with the old AppInit_DLL installer.

**Regarding C#:** Yes, it is possible and very trivial. Have a look at Intall.cpp. All it does is this:

1. Read the stager executable from the resources and write it to two registry keys
2. Create two scheduled tasks, and run both

(on Windows x86, do each task only once)

Install.cpp has source code comments that explain how the installation is implemented.

I won't port it to C#, but it should be fairly trivial to implement the installer as a C# method in your project. The file InstallStager.exe contains both DLL's and the r77 service. I'd also recommend you to read my documentation as it describes the complete process and what exactly to consider when using the rootkit.

You can basically write a downloader for InstallStub.exe.

**Comment by TheDarkMythos** [comment] 2021-03-28 14:10
Great!! thank you for taking the time to answer me!! You have done great work here!! I will take a look yes!

**Comment by bytecode77** [comment] 2021-03-28 15:37
Glad to hear everything is working as expected :)

I've also updated the documentation with best practices for implemenation. It's not yet on the website as a PDF. But the dev-branch contains the current Documentation.docx

**Closed by bytecode77** 2021-03-28 15:37 UTC
